name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: Provider
      description: Which provider are you trying to convert from?
      options:
        - Postman
        - Apidog
        - Bruno
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: input-file
    attributes:
      label: Input File (if applicable)
      description: If possible, please share a sample input file or a minimal example that reproduces the issue. You can attach files or paste relevant snippets.
      placeholder: Paste relevant file content or describe the structure...

  - type: textarea
    id: output
    attributes:
      label: Output/Error Message
      description: If applicable, paste the output or error message you received.
      placeholder: Paste error message or output here...
      render: shell

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      options:
        - "18.x"
        - "20.x"
        - "22.x"
        - Other
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of @gyeonghokim/openapi-converter are you using?
      placeholder: e.g., 1.0.0

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Additional information about your environment
      placeholder: |
        - OS: [e.g., macOS, Linux, Windows]
        - Shell: [e.g., zsh, bash]
        - Any other relevant details

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem here.
      placeholder: Any additional information...

